version: '3.8'
services:
  app-scratch:
    image: webdevops/php-apache:8.1-alpine
    container_name: app_scratch
    volumes:
      - ./:/app
    ports:
      - 4200:80
  mysql-scratch:
    image: mysql:latest
    container_name: mysql_scratch
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - 9090:3306